# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

# emerg, alert, crit, err, warning, notice, info y debug,

prod:
  logger:
    class:   sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
      format:      %time% %type% [%priority%] %message%%EOL%
      time_format: %Y-%m-%d %H:%M:%S

  mailer:
    param:
      delivery_strategy: realtime

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: realtime

dev:
  mailer:
    param:
      delivery_strategy: realtime

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  storage:
    class: sfSessionStorage
    param:
      session_name: SgArqBase

  user:
    class: myUser
    param:
      timeout: 1800 # 30 minutos para expirar la sesion de usuario

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    class: sfMailer
    param:
      logging: %SF_LOGGING_ENABLED%
      charset: %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: 192.168.3.225
          port: 25
          encryption: ~
          username: ~
          password: ~
  
