<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent {

    public function getStartWithFormat($format = 'd/m/Y') {
        if ($this->getStart() && $this->getStart() != "" && $this->getStart() != "0000-00-00 00:00:00")
            return Util::convertToDate($this->getStart(), 'Y-m-d H:i:s', $format);
        return false;
    }

    public function getEndWithFormat($format = 'd/m/Y') {
        if ($this->getEnd() && $this->getEnd() != "" && $this->getEnd() != "0000-00-00 00:00:00")
            return Util::convertToDate($this->getEnd(), 'Y-m-d H:i:s', $format);
        return false;
    }

    public function getAsArray() {
        $result = $this->toArray();

        $result['Calendar'] = $this->getCalendar()->toArray();
        $result['Reminder'] = $this->getReminder()->toArray();
        
        return $result;
    }

}