<?php

/**
 * ModuleDependencyRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuleDependencyRelationTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ModuleDependencyRelationTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ModuleDependencyRelation');
    }

}