<?php

/**
 * ModulePermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModulePermissionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ModulePermissionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ModulePermission');
    }
}