<?php

/**
 * Note
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Note extends BaseNote {

    public function getIdent() {
        $note = $this->getNote();
        $amount = 0;
        while ($note->getId() > 0) {
            $amount++;
            $note = $note->getNote();
        }

        return $amount;
    }

    public function toArray($deep = true, $prefixKey = false) {
        $array = parent::toArray($deep, $prefixKey);
        $array['ident'] = $this->getIdent();
        $array['Person'] = $this->getPerson()->toArray(true);
        
        return $array;
    }
	
    public static function getJsonAsKeysValues($jsontext) {
		$json = json_decode($jsontext, true);
		
		//[["dateField","numberField","contractField"],["2020-12-05T00:00:00","1","202012-22"],["05/12/2020","1","202012-22"],["","Contract::getSuplementNumber",""]]
		//[["dateField","reclamationtypeCombo","numberField","hiddenField","receptiondateField","reclamaionstatusCombo"],["2020-12-06T00:00:00",1,"","","2020-12-16T00:00:00",""],["06/12/2020","Impagos","","","16/12/2020",""],["","","Contract::getReclamationNumber","","",""]]
		
		$array = array();
		for($index = 0; $index < count($json[0]); $index++)
			$array[$json[0][$index]] = array(
				'value' => $json[1][$index],
				'raw' => $json[2][$index],
				'function' => $json[3][$index],
			);

		return $array;
	}

}