<?php

/**
 * Entity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfEntity extends BaseEntity {

    public function isUsed() {
        return false;
    }

    public function getReview() {
        $q = Doctrine_Query::create()
                ->select('r.*, COUNT(r.id) as total, AVG(r.amount) as average')
                ->from('Note r')
                ->where('r.entity = ? AND r.entityid = ? AND r.amount is not NULL', array('Entity', $this->getId()));
        $review = $q->fetchOne()->toArray();

        $obj = new stdClass();
        $obj->reviews = $review['total'];
        $obj->amount = round($review['average']);

        return $obj;
    }

}
