<?php

/**
 * Person
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfPerson extends BasePerson {

    public function getAsArray() {
        $array = $this->toArray();  
        $array['sfGuardUser'] = $this->getSfGuardUser()->toArray();
        $array['fullname'] = $this->getFullName();
        
        return $array;
    }

    public function getFullName() {
        $fullname = '';
        if ($this->getSfGuardUser())
            $fullname = $this->getSfGuardUser()->getFirstName() . ' ' . $this->getSfGuardUser()->getLastName();
        return $fullname;
    }

}